# Generated by Django 3.2.6 on 2021-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_s',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('speech', models.CharField(max_length=1250)),
            ],
            options={
                'db_table': 'about_m',
            },
        ),
        migrations.CreateModel(
            name='Appli',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('Father', models.CharField(max_length=50)),
                ('Mother', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('DateBirth', models.DateField()),
                ('Category', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Disability', models.CharField(max_length=50)),
                ('AddressLine1', models.CharField(max_length=50)),
                ('AddressLine2', models.CharField(max_length=50)),
                ('AddressLine3', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Highest_Educational_Qualification', models.CharField(max_length=150)),
                ('YearOfPassing', models.IntegerField()),
                ('Aadhar_Card_Number', models.IntegerField()),
                ('Upload_Photo', models.ImageField(upload_to='shop/image')),
                ('Upload_Signature', models.ImageField(upload_to='shop/image')),
                ('Left_Hand_Thumb_Impression', models.ImageField(upload_to='shop/image')),
            ],
            options={
                'db_table': 'Appli',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=40)),
                ('sgmail', models.CharField(max_length=50)),
                ('smessage', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('Gmail', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='InqueryForm',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('gmail', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'InqueryForm',
            },
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('Fathername', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('course', models.CharField(max_length=40)),
                ('gmail', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Provisional',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('sno', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Provisional',
            },
        ),
        migrations.CreateModel(
            name='Reviewdata',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(blank=True, default='', max_length=50)),
                ('m', models.CharField(blank=True, default='', max_length=1250)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
