# Generated by Django 3.2.6 on 2021-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('comment_name', models.CharField(max_length=50)),
                ('comment_message', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.DeleteModel(
            name='Reviewdata',
        ),
    ]
