# Generated by Django 3.2.6 on 2021-08-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20210831_2223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
