# Generated by Django 3.2.6 on 2021-08-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
